apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
  namespace: default
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  params:
    - name: image
      type: string
      description: the container image to deploy
  results:
    - name: url
      description: the URL where the app is deployed to
  steps:
    - name: deploy
      image: docker.io/bitnami/kubectl@sha256:792e0aaabee6c51d734b5d3b150ba990d6106c4c081731d8570c1b9afe0c52d9
      script: |
        #!/bin/sh
        set -ex

        # Try to create a deployment, in case it's our first run
        kubectl create deployment cdcon-demo --image $(params.image) || true

        # Update the deployment, rollout new image
        kubectl set image deployment/cdcon-demo *=$(params.image)

        # Create a service if it doesn't exists yet
        kubectl expose deployment/cdcon-demo --port 8080 --target-port 80 || true

        # Make sure we run at least two pods
        kubectl scale --replicas=2 deployment/cdcon-demo