apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cdcon-demo
spec:
  params:
    - name: registry
      type: string
      default: uk.icr.io/tekton
    - name: revision
      type: string
      default: main
    - name: target
      type: string
      default: demo
  workspaces:
    - name: source
    - name: dockerconfig
      optional: true
  results:
    - name: git-sha
      description: the git sha that has been built
      value: $(tasks.clone.results.commit)
    - name: image-sha
      description: the sha of the target container image
      value: $(tasks.build.results.IMAGE-DIGEST)
    - name: app-url
      description: the URL to reach the deployed app
      value: $(tasks.deploy.results.url)
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/afrittoli/scaling_pipelines_with_tekton
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: build
      runAfter: ['clone']
      taskRef:
        name: kaniko
        bundle: gcr.io/tekton-releases/catalog/upstream/kaniko:0.3
      params:
        - name: IMAGE
          value: $(params.registry)/zero2tekton:$(tasks.clone.results.commit)
        - name: CONTEXT
          value: images/demo
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
    - name: deploy
      runAfter: ['build']
      taskRef:
        name: deploy-with-ingress
        bundle: uk.icr.io/tekton/catalog/demo/deploy-with-ingress:0.1
      params:
        - name: image
          value: $(params.registry)/zero2tekton@$(tasks.build.results.IMAGE-DIGEST)
        - name: target
          value: $(params.target)